name: Frontend Build
on:
    push:
        branches: 
            - main
        paths: 
            - "frontend/**"
        
    pull_request: 
        types: [opened,synchronize,reopened]
    
jobs:
    frontend:
        name: FE testing
        runs-on: ubuntu-latest
        timeout-minutes: 3
        defaults:
            run:
                working-directory: frontend
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Checking the frontend changes
          run: echo "Frontend changes done"

        
              
